[build-system]
requires = ["setuptools >= 40.8.0", "wheel", "click"]
build-backend = "setuptools.build_meta:__legacy__"

[tool.black]
line-length = 120
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.nox
  | \.venv
  | _build
  | build
  | dist
)/
'''

